services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6381:6379"
    command: redis-server --requirepass ${REDIS__PASSWORD} --appendonly yes

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: ${POSTGRES__USER}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD}
      POSTGRES_DB: ${POSTGRES__DB}

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_panel
    restart: always
    ports:
      - "5045:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres

  chat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat
    restart: always
    environment:
      - PYTHONPATH=/chat-service
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/chat-service

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB__USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB__PASSWORD}